name: Export open-lc image

on:
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull ghcr.io/leuki/open-lc:latest

      - name: Save image
        run: docker save ghcr.io/leuki/open-lc:latest -o open-lc-latest.tar

      - name: Compress
        run: zstd -19 open-lc-latest.tar -o open-lc-latest.tar.zst

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: open-lc-latest-image
          path: open-lc-latest.tar.zst
